version: '0.9.0+{build}'
image: Visual Studio 2017
skip_branch_with_pr: true
skip_commits:
  files:
  - '**/*.md'
build:
  verbosity: minimal
services:
  - mongodb
install:
#  - choco install opencover codecov
  - ps: .\build\dotnet-install.ps1 -Version 3.0.100-preview-009812


build_script:
  - dotnet build -c Release
test_script:
  - dotnet test MongoFramework.Tests/MongoFramework.Tests.csproj -v minimal
#  - OpenCover.Console.exe -register:user -target:"C:\Users\appveyor\AppData\Local\Microsoft\dotnet\dotnet.exe" -targetargs:"test MongoFramework.Tests/MongoFramework.Tests.csproj" -filter:"+[MongoFramework]* -[MongoFramework.Tests]*" -output:".\coverage.xml" -oldstyle
#  - codecov -f coverage.xml


artifacts:
  - path: 'MongoFramework\bin\Release\*.nupkg'
    name: NuGet Package

  - path: coverage.xml
    name: Coverage Report