version: '0.9.0+{build}'
image: Visual Studio 2017
skip_branch_with_pr: true
skip_commits:
  files:
  - '**/*.md'
build:
  verbosity: minimal
services:
  - mongodb
install:
  - choco install opencover codecov
  - ps: [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -useb 'https://dot.net/v1/dotnet-install.ps1'))) -Version 3.0.100-preview-009812


build_script:
  - dotnet build -c Debug
  - dotnet build -c Release
test_script:
  - OpenCover.Console.exe -register:user -target:"dotnet" -targetargs:"test MongoFramework.Tests/MongoFramework.Tests.csproj" -filter:"+[MongoFramework]* -[MongoFramework.Tests]*" -output:".\coverage.xml" -oldstyle
  - codecov -f coverage.xml


artifacts:
  - path: 'MongoFramework\bin\Debug\*.nupkg'
    name: NuGet Package (Debug)

  - path: 'MongoFramework\bin\Release\*.nupkg'
    name: NuGet Package (Release)

  - path: coverage.xml
    name: Coverage Report