version: '{build}'
image: Visual Studio 2017
build:
  verbosity: minimal
services:
  - mongodb
install:
  - choco install opencover codecov


before_build:
  - nuget restore -Verbosity quiet
build_script:
  - msbuild MongoFramework.sln /verbosity:minimal /p:DebugType=full /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test_script:
  - OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"/logger:Appveyor MongoFramework.Tests\bin\Debug\MongoFramework.Tests.dll" -filter:"+[MongoFramework]* -[MongoFramework.Tests]*" -output:".\coverage.xml"
  - codecov -f coverage.xml


artifacts:
  - path: 'MongoFramework\bin\Debug\*.nupkg'
    name: NuGet Package

  - path: coverage.xml
    name: Coverage Report